services:
  mysql:
    image: mysql:8.4
    container_name: edu_platform_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edu_platform
      MYSQL_USER: edu_platform
      MYSQL_PASSWORD: secret

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8-alpine
    container_name: edu_platform_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

